FROM node:18-alpine AS builder
WORKDIR /app

COPY src/WhoIAm.Web/package*.json ./
RUN npm install

COPY src/WhoIAm.Web/ ./
RUN npm run build

FROM node:18-alpine
WORKDIR /app

RUN npm install -g serve
COPY --from=builder /app/dist ./dist

EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]
